version: '3'

networks:
  appnetwork:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-service
    ports:
      - "8088:80"
    volumes:
      - ./public_html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log/error.log:/var/log/nginx/error.log
      - ./nginx/log/access.log:/var/log/nginx/access.log
    depends_on:
      - php
      - mysql
    networks:
      - appnetwork

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3366:3306"
    volumes:
      - ./.database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: webapp
      MYSQL_USER: root
      MYSQL_PASSWORD: password1
      MYSQL_ROOT_PASSWORD: password1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - appnetwork

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-service
    volumes:
      - ./public_html:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - appnetwork
  
  phpmyadmin:
        image: phpmyadmin:5.1.0-apache
        container_name: phpmyadmin
        restart: unless-stopped
        ports: 
            - 8200:80
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: password1
        networks:
            - appnetwork
